### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by vermaden** [isene/IMDB#1]
Hi,

I have fetched it and tried to run it on FreeBSD but it fails/hangs.

I provided all 3 needed API keys.

Here is what it looks on my terminal:

```
~/_imdb/IMDB-main % ./imdb

No network. Running offline.

Loading IMDB data... (this may take som time, go get some coffee)
/usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 502 Bad Gateway (RestClient::BadGateway)
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/local/lib/ruby/3.1/net/http.rb:985:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from ./imdb:412:in `getimdb'
        from ./imdb:425:in `loadimdb'
        from ./imdb:726:in `<main>'

```

These are my Ruby versions and packages:

```
% pkg info | grep ruby | awk '{print $1}'
ruby-3.1.4_1,1
ruby31-gems-3.4.15
rubygem-curses-1.3.2
rubygem-domain_name-0.5.20190701
rubygem-http-accept-2.2.0
rubygem-http-cookie-1.0.5
rubygem-mime-types-3.4.1
rubygem-mime-types-data-3.2023.0218.1
rubygem-netrc-0.11.0
rubygem-rest-client-2.1.0
rubygem-unf-0.1.4
rubygem-unf_ext-0.0.8.2

```

Regards.

**Comment by isene** [comment]
Thanks for testing this on freebsd (if you like, please check out my other repos and see if anything tickles you fancy - would love to have more tested on freebsd),

1. Do you have network access when you test it?
2. Could you paste your .imdb.conf here (removing the api keys inside the quotation marks)?

**Comment by vermaden** [comment]
Thanks for reply, yes I have the network access.

Something different now :)

```
% ping -c 3 imdb.com              
PING imdb.com (52.94.225.248): 56 data bytes
64 bytes from 52.94.225.248: icmp_seq=0 ttl=236 time=199.989 ms
64 bytes from 52.94.225.248: icmp_seq=1 ttl=236 time=214.263 ms
64 bytes from 52.94.225.248: icmp_seq=2 ttl=236 time=134.035 ms

--- imdb.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 134.035/182.762/214.263/34.945 ms

% ./_imdb/IMDB-main/imdb 
Loading IMDB data... (this may take som time, go get some coffee)
./_imdb/IMDB-main/imdb:664:in `w_b': undefined method `clr' for nil:NilClass (NoMethodError)

  @w_b.clr
      ^^^^
        from ./_imdb/IMDB-main/imdb:538:in `saveimdb'
        from ./_imdb/IMDB-main/imdb:727:in `<main>'

```

... but when executed in the dir:

```
% pwd
~/_imdb/IMDB-main

% ./imdb 
Loading IMDB data... (this may take som time, go get some coffee)
/usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:249:in `exception_with_response': 502 Bad Gateway (RestClient::BadGateway)
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/abstract_response.rb:129:in `return!'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:836:in `process_result'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:743:in `block in transmit'
        from /usr/local/lib/ruby/3.1/net/http.rb:985:in `start'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:727:in `transmit'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:163:in `execute'
        from /usr/local/lib/ruby/gems/3.1/gems/rest-client-2.1.0/lib/restclient/request.rb:63:in `execute'
        from ./imdb:412:in `getimdb'
        from ./imdb:425:in `loadimdb'
        from ./imdb:726:in `<main>'

```

Regards,
vermaden

**Comment by vermaden** [comment]
... and I forgot the config, its just the APIs:

```
% cat ~/.imdb.conf   
@imdbkey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
@omdbkey = 'xxxxxxxx'
@streamkey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
              

```

**Comment by isene** [comment]
Complete rewrite after this issue was reported.

**Comment by vermaden** [comment]
> Complete rewrite after this issue was reported.

Does it now work under FreeBSD?

**Comment by isene** [comment]
I have no easy way of checking. If you or anyone would like to test this completely rewritten application on freebsd - feel free :)

**Comment by vermaden** [comment]
OK, will test latest version when I find some time, thanks :)
